# Generated by Django 4.2.19 on 2025-03-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(default='to do', max_length=50)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
