# Generated by Django 4.2.19 on 2025-05-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0008_alter_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default='No description', null=True),
        ),
    ]
